name: Tests
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Generate cosmjs types
        run: yarn run codegen
        working-directory: ./packages/core

      - name: Test
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest-m
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn
        working-directory: ./packages/core

      - name: Generate cosmjs types
        run: yarn run codegen
        working-directory: ./packages/core

      - name: Setup starship
        run: yarn run e2e:setup HELM_FILE=starship/ci.yaml
        working-directory: ./packages/core

      - name: Start starship
        run: make start HELM_FILE=starship/ci.yaml
        working-directory: ./packages/core

      - name: Run e2e tests
        run: yarn run e2e:test
        working-directory: ./packages/core
